name: Build and Attach to Release

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build project
        run: dotnet build --configuration Debug

      - name: Upload DLL to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/Debug/net8.0/DanhengPlugin-DHConsoleCommands.dll
          asset_name: DanhengPlugin-DHConsoleCommands.dll
          asset_content_type: application/octet-stream
